<?php
$DBDATABASE="inventory";
$DBUSERNAME="root";
$DBPASSWORD="";
$CONNECTION=mysqli_connect("localhost",$DBUSERNAME,$DBPASSWORD,$DBDATABASE);
$MOBILENUMBERDIGIT=10;
$LANDLINENUMBERDIGIT=10;
$BASEURL="/inventory/ ";
?>
