md openworld.co.ke zimbraAutoProvAccountNameMap "sAMAccountName"
md openworld.co.ke zimbraAutoProvAttrMap "sn=sn"
md openworld.co.ke +zimbraAutoProvAttrMap "description=description"
md openworld.co.ke +zimbraAutoProvAttrMap "cn=displayName"
md openworld.co.ke +zimbraAutoProvAttrMap "givenName=givenName"
md openworld.co.ke zimbraAutoProvBatchSize "20"
md openworld.co.ke zimbraAutoProvLdapAdminBindDn "cn=Administrator,cn=users,dc=openworld,dc=co,dc=ke"
md openworld.co.ke zimbraAutoProvLdapAdminBindPassword "Admin1234"
md openworld.co.ke zimbraAutoProvLdapBindDn "cn=Administrator,cn=users,dc=openworld,dc=co,dc=ke"
md openworld.co.ke zimbraAutoProvLdapSearchBase "dc=openworld,dc=co,dc=ke"
md openworld.co.ke zimbraAutoProvLdapSearchFilter "(&(ObjectCategory=person))"
md openworld.co.ke zimbraAutoProvLdapURL "ldap://192.168.111.115:389"
md openworld.co.ke zimbraAutoProvMode "EAGER"
md openworld.co.ke zimbraAutoProvNotificationBody "Your account has been auto provisioned. Your email address is ${ACCOUNT_ADDRESS}."
md openworld.co.ke zimbraAutoProvNotificationFromAddress "administrator@openworld.co.ke"
md openworld.co.ke zimbraAutoProvNotificationSubject "New account auto provisioned"
ms mail.openworld.co.ke zimbraAutoProvPollingInterval "1m"
ms mail.openworld.co.ke zimbraAutoProvScheduledDomains "openworld.co.ke"
